export const requestData = [
  {
    id: 1,
    image: require('../../assets/request.png'),
    title: 'End Poverty Welfare Society',
    details: "We are in need of 15 food packets in Sariya's Sip N Bites!Location before 1:30 PM",
    time: '5 hours ago',
    quantity: 15,
    location: 'Lahore',
    deliver: '2:30 pm',
  },
  {
    id: 2,
    image: require('../../assets/request.png'),
    title: 'End Poverty Welfare Society',
    details: "We are in need of 15 food packets in Sariya's Sip N Bites!Location before 1:30 PM",
    time: '5 hours ago',
    quantity: 15,
    location: 'Lahore',
    deliver: '2:30 pm',
  },
  {
    id: 3,
    image: require('../../assets/request.png'),
    title: 'End Poverty Welfare Society',
    details: "We are in need of 15 food packets in Sariya's Sip N Bites!Location before 1:30 PM",
    time: '5 hours ago',
    quantity: 15,
    location: 'Lahore',
    deliver: '2:30 pm',
  },
  {
    id: 4,
    image: require('../../assets/request.png'),
    title: 'End Poverty Welfare Society',
    details: "We are in need of 15 food packets in Sariya's Sip N Bites!Location before 1:30 PM",
    time: '5 hours ago',
    quantity: 15,
    location: 'Lahore',
    deliver: '2:30 pm',
  },
  {
    id: 5,
    image: require('../../assets/request.png'),
    title: 'End Poverty Welfare Society',
    details: "We are in need of 15 food packets in Sariya's Sip N Bites!Location before 1:30 PM",
    time: '5 hours ago',
    quantity: 15,
    location: 'Lahore',
    deliver: '2:30 pm',
  },
  {
    id: 6,
    image: require('../../assets/request.png'),
    title: 'End Poverty Welfare Society',
    details: "We are in need of 15 food packets in Sariya's Sip N Bites!Location before 1:30 PM",
    time: '5 hours ago',
    quantity: 15,
    location: 'Lahore',
    deliver: '2:30 pm',
  },
]
